//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuferMAN.Plugins {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuferMAN.Plugins.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery saver mode.
        /// </summary>
        internal static string BatterySaverPlugin {
            get {
                return ResourceManager.GetString("BatterySaverPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please charge your battery ({0}%) in order to save your battery&apos;s health.
        /// </summary>
        internal static string BatterySaverPluginChargeNoteFormat {
            get {
                return ResourceManager.GetString("BatterySaverPluginChargeNoteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please uncharge your battery ({0}%) in order to save your battery&apos;s health.
        /// </summary>
        internal static string BatterySaverPluginUnchargeNoteFormat {
            get {
                return ResourceManager.GetString("BatterySaverPluginUnchargeNoteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many characters....
        /// </summary>
        internal static string BigTextBufer {
            get {
                return ResourceManager.GetString("BigTextBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big text bufer.
        /// </summary>
        internal static string BigTextBuferPlugin {
            get {
                return ResourceManager.GetString("BigTextBuferPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder about BuferMAN.
        /// </summary>
        internal static string BufermanReminderPlugin {
            get {
                return ResourceManager.GetString("BufermanReminderPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel deletion (at {0}).
        /// </summary>
        internal static string CancelDeferredDeletionMenuItem {
            get {
                return ResourceManager.GetString("CancelDeferredDeletionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bufer will be deleted at {0}.
        /// </summary>
        internal static string DeferredBuferDeletionTime {
            get {
                return ResourceManager.GetString("DeferredBuferDeletionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferred bufer deletion plugin.
        /// </summary>
        internal static string DeferredBuferPlugin {
            get {
                return ResourceManager.GetString("DeferredBuferPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In {0} minutes.
        /// </summary>
        internal static string DeleteBuferInNMinutesMenuItem {
            get {
                return ResourceManager.GetString("DeleteBuferInNMinutesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Now.
        /// </summary>
        internal static string DeleteBuferNowMenuItem {
            get {
                return ResourceManager.GetString("DeleteBuferNowMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC cleaner.
        /// </summary>
        internal static string PCCleanerPlugin {
            get {
                return ResourceManager.GetString("PCCleanerPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All you need is BuferMAN: Alt +C !.
        /// </summary>
        internal static string ReminderPluginText {
            get {
                return ResourceManager.GetString("ReminderPluginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts.
        /// </summary>
        internal static string ScriptsPlugin {
            get {
                return ResourceManager.GetString("ScriptsPlugin", resourceCulture);
            }
        }
    }
}
