//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuferMAN.Menu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuferMAN.Menu.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Documentation.
        /// </summary>
        internal static string DocumentationMenuItem {
            get {
                return ResourceManager.GetString("DocumentationMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &amp;all.
        /// </summary>
        internal static string MenuEditDel {
            get {
                return ResourceManager.GetString("MenuEditDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all &amp;temporary.
        /// </summary>
        internal static string MenuEditDelTemp {
            get {
                return ResourceManager.GetString("MenuEditDelTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are pinned bufers exist. Do you want to delete only temporal bufers?.
        /// </summary>
        internal static string MenuEditDelText {
            get {
                return ResourceManager.GetString("MenuEditDelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm pinned bufers deletion.
        /// </summary>
        internal static string MenuEditDelTitle {
            get {
                return ResourceManager.GetString("MenuEditDelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string MenuEditRedo {
            get {
                return ResourceManager.GetString("MenuEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string MenuEditUndo {
            get {
                return ResourceManager.GetString("MenuEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Update default file.
        /// </summary>
        internal static string MenuFileChangeDefault {
            get {
                return ResourceManager.GetString("MenuFileChangeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit session.
        /// </summary>
        internal static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Load bufers from file.
        /// </summary>
        internal static string MenuFileLoad {
            get {
                return ResourceManager.GetString("MenuFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause bufers catching.
        /// </summary>
        internal static string MenuFilePause {
            get {
                return ResourceManager.GetString("MenuFilePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Restore the latest session.
        /// </summary>
        internal static string MenuFileRestoreSession {
            get {
                return ResourceManager.GetString("MenuFileRestoreSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Resume bufers catching.
        /// </summary>
        internal static string MenuFileResume {
            get {
                return ResourceManager.GetString("MenuFileResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows clipboard helper with love... Current program version is.
        /// </summary>
        internal static string MenuHelpAboutText {
            get {
                return ResourceManager.GetString("MenuHelpAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About BuferMAN.
        /// </summary>
        internal static string MenuHelpAboutTitle {
            get {
                return ResourceManager.GetString("MenuHelpAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make &amp;world better.
        /// </summary>
        internal static string MenuHelpDonate {
            get {
                return ResourceManager.GetString("MenuHelpDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello my Friend! Thank you for interest to this program! It was created with love to help other people in their day-to-day activities. The most valuable gift for me will be your help for other people! There are many people who need your help and support around: people with disabilities, children without parents and so on... You can find any charity organization or smthg similar and transfer there some funds - I will really appreciate your act!.
        /// </summary>
        internal static string MenuHelpDonateText {
            get {
                return ResourceManager.GetString("MenuHelpDonateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your help is really appreciated.
        /// </summary>
        internal static string MenuHelpDonateTitle {
            get {
                return ResourceManager.GetString("MenuHelpDonateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an issue.
        /// </summary>
        internal static string MenuHelpReport {
            get {
                return ResourceManager.GetString("MenuHelpReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send &amp;feedback/issue.
        /// </summary>
        internal static string MenuHelpSend {
            get {
                return ResourceManager.GetString("MenuHelpSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Statistics.
        /// </summary>
        internal static string MenuHelpStats {
            get {
                return ResourceManager.GetString("MenuHelpStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program was started at {0}. Copied bufers count: {1} ({2} for today)..
        /// </summary>
        internal static string MenuHelpStatsInfo {
            get {
                return ResourceManager.GetString("MenuHelpStatsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string MenuHelpStatsTitle {
            get {
                return ResourceManager.GetString("MenuHelpStatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins management.
        /// </summary>
        internal static string MenuPluginsManagement {
            get {
                return ResourceManager.GetString("MenuPluginsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Language.
        /// </summary>
        internal static string MenuToolsLanguage {
            get {
                return ResourceManager.GetString("MenuToolsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string MenuToolsLanguageEn {
            get {
                return ResourceManager.GetString("MenuToolsLanguageEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string MenuToolsLanguageRu {
            get {
                return ResourceManager.GetString("MenuToolsLanguageRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;RAM.
        /// </summary>
        internal static string MenuToolsMemory {
            get {
                return ResourceManager.GetString("MenuToolsMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM usage.
        /// </summary>
        internal static string MenuToolsMemoryCaption {
            get {
                return ResourceManager.GetString("MenuToolsMemoryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuferMAN takes {0} KB of RAM..
        /// </summary>
        internal static string MenuToolsMemoryMessageFormat {
            get {
                return ResourceManager.GetString("MenuToolsMemoryMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        internal static string MenuToolsOptions {
            get {
                return ResourceManager.GetString("MenuToolsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Plugins.
        /// </summary>
        internal static string MenuToolsPlugins {
            get {
                return ResourceManager.GetString("MenuToolsPlugins", resourceCulture);
            }
        }
    }
}
