//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardViewerForm.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardViewerForm.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bufer alias was returned to its primary value.
        /// </summary>
        internal static string BuferAliasReturned {
            get {
                return ResourceManager.GetString("BuferAliasReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you need save login/password pair, just use &apos;Create login credentials menu&apos;..
        /// </summary>
        internal static string ChangeTextPostfix {
            get {
                return ResourceManager.GetString("ChangeTextPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter a new text for this bufer. It can be useful to hide copied passwords or alias some enourmous text. Primary button value was.
        /// </summary>
        internal static string ChangeTextPrefix {
            get {
                return ResourceManager.GetString("ChangeTextPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change bufer&apos;s text.
        /// </summary>
        internal static string ChangeTextTitle {
            get {
                return ResourceManager.GetString("ChangeTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TAB between username and password will be inserted automatically as well as Enter after password..
        /// </summary>
        internal static string CreateCredsPostfix {
            get {
                return ResourceManager.GetString("CreateCredsPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter a password for login name.
        /// </summary>
        internal static string CreateCredsPrefix {
            get {
                return ResourceManager.GetString("CreateCredsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create login credentials.
        /// </summary>
        internal static string CreateCredsTitle {
            get {
                return ResourceManager.GetString("CreateCredsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste username.
        /// </summary>
        internal static string CredsName {
            get {
                return ResourceManager.GetString("CredsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste password.
        /// </summary>
        internal static string CredsPassword {
            get {
                return ResourceManager.GetString("CredsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste password with Enter.
        /// </summary>
        internal static string CredsPasswordEnter {
            get {
                return ResourceManager.GetString("CredsPasswordEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creds for.
        /// </summary>
        internal static string CredsPrefix {
            get {
                return ResourceManager.GetString("CredsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password can not be empty or whitespaces. Try again! Try better!.
        /// </summary>
        internal static string EmptyPasswordError {
            get {
                return ResourceManager.GetString("EmptyPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        internal static string FileBufer {
            get {
                return ResourceManager.GetString("FileBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files.
        /// </summary>
        internal static string FilesBufer {
            get {
                return ResourceManager.GetString("FilesBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image.
        /// </summary>
        internal static string ImageBufer {
            get {
                return ResourceManager.GetString("ImageBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is an error during reading a file.
        /// </summary>
        internal static string LoadFileErrorPrefix {
            get {
                return ResourceManager.GetString("LoadFileErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading file error.
        /// </summary>
        internal static string LoadFileErrorTitle {
            get {
                return ResourceManager.GetString("LoadFileErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text files (*.txt)|*.txt.
        /// </summary>
        internal static string LoadFileFilter {
            get {
                return ResourceManager.GetString("LoadFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login credentials.
        /// </summary>
        internal static string LoginCreds {
            get {
                return ResourceManager.GetString("LoginCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login with creds.
        /// </summary>
        internal static string LoginWith {
            get {
                return ResourceManager.GetString("LoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Added to &amp;bufers.txt file.
        /// </summary>
        internal static string MenuAddedToFile {
            get {
                return ResourceManager.GetString("MenuAddedToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add to &amp;bufers.txt file.
        /// </summary>
        internal static string MenuAddToFile {
            get {
                return ResourceManager.GetString("MenuAddToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change &amp;text.
        /// </summary>
        internal static string MenuChange {
            get {
                return ResourceManager.GetString("MenuChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type &amp;char by char (for console).
        /// </summary>
        internal static string MenuCharByChar {
            get {
                return ResourceManager.GetString("MenuCharByChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create &amp;login credentials.
        /// </summary>
        internal static string MenuCreds {
            get {
                return ResourceManager.GetString("MenuCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Delete.
        /// </summary>
        internal static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Edit.
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete &amp;all.
        /// </summary>
        internal static string MenuEditDel {
            get {
                return ResourceManager.GetString("MenuEditDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all &amp;temporary.
        /// </summary>
        internal static string MenuEditDelTemp {
            get {
                return ResourceManager.GetString("MenuEditDelTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are persistent bufers exist. Do you want to delete only temporal bufers?.
        /// </summary>
        internal static string MenuEditDelText {
            get {
                return ResourceManager.GetString("MenuEditDelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm persistent bufers deletion.
        /// </summary>
        internal static string MenuEditDelTitle {
            get {
                return ResourceManager.GetString("MenuEditDelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Redo.
        /// </summary>
        internal static string MenuEditRedo {
            get {
                return ResourceManager.GetString("MenuEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Undo.
        /// </summary>
        internal static string MenuEditUndo {
            get {
                return ResourceManager.GetString("MenuEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E&amp;xit session.
        /// </summary>
        internal static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lo&amp;ad from file.
        /// </summary>
        internal static string MenuFileLoad {
            get {
                return ResourceManager.GetString("MenuFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Formats.
        /// </summary>
        internal static string MenuFormats {
            get {
                return ResourceManager.GetString("MenuFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;About.
        /// </summary>
        internal static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows clipboard helper with love... Version.
        /// </summary>
        internal static string MenuHelpAboutText {
            get {
                return ResourceManager.GetString("MenuHelpAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About BuferMAN.
        /// </summary>
        internal static string MenuHelpAboutTitle {
            get {
                return ResourceManager.GetString("MenuHelpAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Donate.
        /// </summary>
        internal static string MenuHelpDonate {
            get {
                return ResourceManager.GetString("MenuHelpDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello my Friend! Thank you for interest to this program! It was created with love to help other people in their day-to-day activities. The most valuable gift for me will be your help for other people! There are many people who need your help and support around: people with disabilities, children without parents and so on... You can find any clarity organization or smthg similar and transfer there some funds - I will really appreciate your act! Thank you again and have a nice day!.
        /// </summary>
        internal static string MenuHelpDonateText {
            get {
                return ResourceManager.GetString("MenuHelpDonateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your help is really appreciated.
        /// </summary>
        internal static string MenuHelpDonateTitle {
            get {
                return ResourceManager.GetString("MenuHelpDonateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send &amp;feedback/issue.
        /// </summary>
        internal static string MenuHelpSend {
            get {
                return ResourceManager.GetString("MenuHelpSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Start time.
        /// </summary>
        internal static string MenuHelpStart {
            get {
                return ResourceManager.GetString("MenuHelpStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program was started at.
        /// </summary>
        internal static string MenuHelpStartPrefix {
            get {
                return ResourceManager.GetString("MenuHelpStartPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start time.
        /// </summary>
        internal static string MenuHelpStartTitle {
            get {
                return ResourceManager.GetString("MenuHelpStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Paste.
        /// </summary>
        internal static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на M&amp;ark as persistent.
        /// </summary>
        internal static string MenuPersistent {
            get {
                return ResourceManager.GetString("MenuPersistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Return text to initial.
        /// </summary>
        internal static string MenuReturn {
            get {
                return ResourceManager.GetString("MenuReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not a text.
        /// </summary>
        internal static string NotTextBufer {
            get {
                return ResourceManager.GetString("NotTextBufer", resourceCulture);
            }
        }
    }
}
