//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuferMAN.WinForms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuferMAN.WinForms.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your bufers pinned. Please remove some of them and then try to copy again....
        /// </summary>
        internal static string AllBufersPinned {
            get {
                return ResourceManager.GetString("AllBufersPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your click on bufer pastes its content into the place where mouse cursor is in or where you are active now.
        /// </summary>
        internal static string BuferClickingExplanationText {
            get {
                return ResourceManager.GetString("BuferClickingExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bufer was loaded from storage.
        /// </summary>
        internal static string BuferLoaded {
            get {
                return ResourceManager.GetString("BuferLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is working in background. Click Alt+C to open..
        /// </summary>
        internal static string ClosingWindowExplanation {
            get {
                return ResourceManager.GetString("ClosingWindowExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: use Esc key to hide the application..
        /// </summary>
        internal static string EscHotKeyExplanation {
            get {
                return ResourceManager.GetString("EscHotKeyExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileBufer {
            get {
                return ResourceManager.GetString("FileBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string FilesBufer {
            get {
                return ResourceManager.GetString("FilesBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string FolderBufer {
            get {
                return ResourceManager.GetString("FolderBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string FoldersBufer {
            get {
                return ResourceManager.GetString("FoldersBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to &amp;default file.
        /// </summary>
        internal static string MenuAddedToFile {
            get {
                return ResourceManager.GetString("MenuAddedToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;in bufer.
        /// </summary>
        internal static string MenuPin {
            get {
                return ResourceManager.GetString("MenuPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin bufer.
        /// </summary>
        internal static string MenuUnpin {
            get {
                return ResourceManager.GetString("MenuUnpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program is launched in not administrator mode. You can not paste bufers into windows launched in admin mode!
        ///
        ///.
        /// </summary>
        internal static string NotAdminWarning {
            get {
                return ResourceManager.GetString("NotAdminWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuferMAN: Alt+C to open.
        /// </summary>
        internal static string NotifyIconStartupText {
            get {
                return ResourceManager.GetString("NotifyIconStartupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a text.
        /// </summary>
        internal static string NotTextBufer {
            get {
                return ResourceManager.GetString("NotTextBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind about Administaror mode.
        /// </summary>
        internal static string OptionsAdministratorModeReminder {
            get {
                return ResourceManager.GetString("OptionsAdministratorModeReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display message box on startup with option to open app in Administrator mode.
        /// </summary>
        internal static string OptionsAdministratorModeReminderTooltip {
            get {
                return ResourceManager.GetString("OptionsAdministratorModeReminderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change color for current clipboard bufer.
        /// </summary>
        internal static string OptionsChangeCurrentClipboardColor {
            get {
                return ResourceManager.GetString("OptionsChangeCurrentClipboardColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change default color for clipboard bufer.
        /// </summary>
        internal static string OptionsChangeDefaultClipboardColor {
            get {
                return ResourceManager.GetString("OptionsChangeDefaultClipboardColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change color for pinned bufer.
        /// </summary>
        internal static string OptionsChangePinnedClipboardColor {
            get {
                return ResourceManager.GetString("OptionsChangePinnedClipboardColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string OptionsCommonTabName {
            get {
                return ResourceManager.GetString("OptionsCommonTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable.
        /// </summary>
        internal static string OptionsFocusBuferEnableDisable {
            get {
                return ResourceManager.GetString("OptionsFocusBuferEnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip on bufer focus.
        /// </summary>
        internal static string OptionsFocusBuferTooltip {
            get {
                return ResourceManager.GetString("OptionsFocusBuferTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (milliseconds).
        /// </summary>
        internal static string OptionsFocusBuferTooltipDurationText {
            get {
                return ResourceManager.GetString("OptionsFocusBuferTooltipDurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string OptionsPluginsTabName {
            get {
                return ResourceManager.GetString("OptionsPluginsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore previous session.
        /// </summary>
        internal static string OptionsRestorePreviousSession {
            get {
                return ResourceManager.GetString("OptionsRestorePreviousSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only text bufers.
        /// </summary>
        internal static string OptionsRestorePreviousSessionTooltip {
            get {
                return ResourceManager.GetString("OptionsRestorePreviousSessionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        internal static string OptionsStartup {
            get {
                return ResourceManager.GetString("OptionsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Appearance.
        /// </summary>
        internal static string OptionsUITabName {
            get {
                return ResourceManager.GetString("OptionsUITabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string OptionsWindowCancelButton {
            get {
                return ResourceManager.GetString("OptionsWindowCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default &amp;&amp; Save.
        /// </summary>
        internal static string OptionsWindowRestoreButton {
            get {
                return ResourceManager.GetString("OptionsWindowRestoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string OptionsWindowSaveButton {
            get {
                return ResourceManager.GetString("OptionsWindowSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tra-ta-ta!!!.
        /// </summary>
        internal static string TratataTitle {
            get {
                return ResourceManager.GetString("TratataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white spaces.
        /// </summary>
        internal static string WhiteSpaces {
            get {
                return ResourceManager.GetString("WhiteSpaces", resourceCulture);
            }
        }
    }
}
