//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuferMAN.ContextMenu.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuferMAN.ContextMenu.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bufer alias was returned to its primary value.
        /// </summary>
        internal static string BuferAliasReturned {
            get {
                return ResourceManager.GetString("BuferAliasReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you need save login/password pair, just use &apos;Create login credentials menu&apos;..
        /// </summary>
        internal static string ChangeTextPostfix {
            get {
                return ResourceManager.GetString("ChangeTextPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter a new text for this bufer. It can be useful to hide copied passwords or alias some enourmous text. Primary button value was.
        /// </summary>
        internal static string ChangeTextPrefix {
            get {
                return ResourceManager.GetString("ChangeTextPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change bufer&apos;s text.
        /// </summary>
        internal static string ChangeTextTitle {
            get {
                return ResourceManager.GetString("ChangeTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create &amp;login credentials.
        /// </summary>
        internal static string CreateCredsMenuItem {
            get {
                return ResourceManager.GetString("CreateCredsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TAB between username and password will be inserted automatically as well as Enter after password..
        /// </summary>
        internal static string CreateCredsPostfix {
            get {
                return ResourceManager.GetString("CreateCredsPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter a password for login name.
        /// </summary>
        internal static string CreateCredsPrefix {
            get {
                return ResourceManager.GetString("CreateCredsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create login credentials.
        /// </summary>
        internal static string CreateCredsTitle {
            get {
                return ResourceManager.GetString("CreateCredsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste username.
        /// </summary>
        internal static string CredsName {
            get {
                return ResourceManager.GetString("CredsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste password.
        /// </summary>
        internal static string CredsPassword {
            get {
                return ResourceManager.GetString("CredsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste password with Enter.
        /// </summary>
        internal static string CredsPasswordEnter {
            get {
                return ResourceManager.GetString("CredsPasswordEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creds for.
        /// </summary>
        internal static string CredsPrefix {
            get {
                return ResourceManager.GetString("CredsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Delete.
        /// </summary>
        internal static string DeleteClipMenuItem {
            get {
                return ResourceManager.GetString("DeleteClipMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password can not be empty or whitespaces. Try again! Try better!.
        /// </summary>
        internal static string EmptyPasswordError {
            get {
                return ResourceManager.GetString("EmptyPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login credentials.
        /// </summary>
        internal static string LoginCreds {
            get {
                return ResourceManager.GetString("LoginCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide bufer &amp;text with alias.
        /// </summary>
        internal static string MenuChange {
            get {
                return ResourceManager.GetString("MenuChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Return text to initial.
        /// </summary>
        internal static string MenuReturn {
            get {
                return ResourceManager.GetString("MenuReturn", resourceCulture);
            }
        }
    }
}
