//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuferMAN.ContextMenu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuferMAN.ContextMenu.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bufer alias was returned to its primary value.
        /// </summary>
        internal static string BuferAliasReturned {
            get {
                return ResourceManager.GetString("BuferAliasReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new text for this bufer. It can be useful to hide copied passwords or alias some enourmous text. If you need save login/password pair, just use &apos;Create login credentials menu&apos;..
        /// </summary>
        internal static string ChangeBigText {
            get {
                return ResourceManager.GetString("ChangeBigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new text for this bufer. It can be useful to hide copied passwords or alias some enourmous text. Primary button value was &quot;{0}&quot;. If you need save login/password pair, just use &apos;Create login credentials menu&apos;..
        /// </summary>
        internal static string ChangeText {
            get {
                return ResourceManager.GetString("ChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change bufer&apos;s text.
        /// </summary>
        internal static string ChangeTextTitle {
            get {
                return ResourceManager.GetString("ChangeTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &amp;login credentials.
        /// </summary>
        internal static string CreateCredsMenuItem {
            get {
                return ResourceManager.GetString("CreateCredsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAB between username and password will be inserted automatically as well as Enter after password..
        /// </summary>
        internal static string CreateCredsPostfix {
            get {
                return ResourceManager.GetString("CreateCredsPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password for login name.
        /// </summary>
        internal static string CreateCredsPrefix {
            get {
                return ResourceManager.GetString("CreateCredsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create login credentials.
        /// </summary>
        internal static string CreateCredsTitle {
            get {
                return ResourceManager.GetString("CreateCredsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste username.
        /// </summary>
        internal static string CredsName {
            get {
                return ResourceManager.GetString("CredsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste password.
        /// </summary>
        internal static string CredsPassword {
            get {
                return ResourceManager.GetString("CredsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste password with Enter.
        /// </summary>
        internal static string CredsPasswordEnter {
            get {
                return ResourceManager.GetString("CredsPasswordEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creds for.
        /// </summary>
        internal static string CredsPrefix {
            get {
                return ResourceManager.GetString("CredsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete bufer.
        /// </summary>
        internal static string DeleteBuferMenuItem {
            get {
                return ResourceManager.GetString("DeleteBuferMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can not be empty or whitespaces. Try again! Try better!.
        /// </summary>
        internal static string EmptyPasswordError {
            get {
                return ResourceManager.GetString("EmptyPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login credentials.
        /// </summary>
        internal static string LoginCreds {
            get {
                return ResourceManager.GetString("LoginCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with creds.
        /// </summary>
        internal static string LoginWith {
            get {
                return ResourceManager.GetString("LoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to &amp;default file.
        /// </summary>
        internal static string MenuAddedToFile {
            get {
                return ResourceManager.GetString("MenuAddedToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string MenuAddToDefaultFile {
            get {
                return ResourceManager.GetString("MenuAddToDefaultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add to file.
        /// </summary>
        internal static string MenuAddToFile {
            get {
                return ResourceManager.GetString("MenuAddToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select file....
        /// </summary>
        internal static string MenuAddToSelectedFile {
            get {
                return ResourceManager.GetString("MenuAddToSelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide bufer &amp;text with alias.
        /// </summary>
        internal static string MenuChange {
            get {
                return ResourceManager.GetString("MenuChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Char by char (for console).
        /// </summary>
        internal static string MenuCharByChar {
            get {
                return ResourceManager.GetString("MenuCharByChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied at {0}.
        /// </summary>
        internal static string MenuCopyingTime {
            get {
                return ResourceManager.GetString("MenuCopyingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Formats.
        /// </summary>
        internal static string MenuFormats {
            get {
                return ResourceManager.GetString("MenuFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open location in File Explorer.
        /// </summary>
        internal static string MenuOpenFileLocation {
            get {
                return ResourceManager.GetString("MenuOpenFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in &amp;browser.
        /// </summary>
        internal static string MenuOpenInBrowser {
            get {
                return ResourceManager.GetString("MenuOpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        internal static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AS IS.
        /// </summary>
        internal static string MenuPasteAsIs {
            get {
                return ResourceManager.GetString("MenuPasteAsIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W/o formatting (as a text).
        /// </summary>
        internal static string MenuPasteAsText {
            get {
                return ResourceManager.GetString("MenuPasteAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;in bufer.
        /// </summary>
        internal static string MenuPin {
            get {
                return ResourceManager.GetString("MenuPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place in bufer without paste.
        /// </summary>
        internal static string MenuPlaceInBufer {
            get {
                return ResourceManager.GetString("MenuPlaceInBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Return text to initial.
        /// </summary>
        internal static string MenuReturn {
            get {
                return ResourceManager.GetString("MenuReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin bufer.
        /// </summary>
        internal static string MenuUnpin {
            get {
                return ResourceManager.GetString("MenuUnpin", resourceCulture);
            }
        }
    }
}
