//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuferMAN.Form.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuferMAN.Form.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All your bufers are persistent. Please remove some of them and then try to copy again....
        /// </summary>
        internal static string AllBufersPersistent {
            get {
                return ResourceManager.GetString("AllBufersPersistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        internal static string FileBufer {
            get {
                return ResourceManager.GetString("FileBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files.
        /// </summary>
        internal static string FilesBufer {
            get {
                return ResourceManager.GetString("FilesBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image.
        /// </summary>
        internal static string ImageBufer {
            get {
                return ResourceManager.GetString("ImageBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clipboard last update was at .
        /// </summary>
        internal static string LastClipboardUpdate {
            get {
                return ResourceManager.GetString("LastClipboardUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E&amp;xit session.
        /// </summary>
        internal static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program is launched in not administrator mode. You can not paste bufers into windows launched in admin mode!
        ///
        ///.
        /// </summary>
        internal static string NotAdminWarning {
            get {
                return ResourceManager.GetString("NotAdminWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You copied 1000 times! You are great copypaster ever!.
        /// </summary>
        internal static string NotifyIcon1000Congrats {
            get {
                return ResourceManager.GetString("NotifyIcon1000Congrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You copied 100 times! Congrats!.
        /// </summary>
        internal static string NotifyIcon100Congrats {
            get {
                return ResourceManager.GetString("NotifyIcon100Congrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BuferMAN: Alt+C to open.
        /// </summary>
        internal static string NotifyIconStartupText {
            get {
                return ResourceManager.GetString("NotifyIconStartupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not a text.
        /// </summary>
        internal static string NotTextBufer {
            get {
                return ResourceManager.GetString("NotTextBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BuferMAN is paused. Alt+P to continue.
        /// </summary>
        internal static string PausedStatus {
            get {
                return ResourceManager.GetString("PausedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BuferMAN is resumed. Enjoy copies!.
        /// </summary>
        internal static string ResumedStatus {
            get {
                return ResourceManager.GetString("ResumedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tra-ta-ta!!!.
        /// </summary>
        internal static string TratataTitle {
            get {
                return ResourceManager.GetString("TratataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click bufer to paste it into active window
        ///Every bufer has a context menu
        ///
        ///
        ///Hot keys:
        ///  - Launch the program: Alt + C
        ///  - Go to the first bufer: X
        ///  - Go to the last bufer: V
        ///  - Tabify through 3 bufers: C
        ///  - Undo/Redo an action: Ctrl + Z, Ctrl + Y
        ///
        ///-&gt; Paste your nice copies!.
        /// </summary>
        internal static string UserManual {
            get {
                return ResourceManager.GetString("UserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на white spaces.
        /// </summary>
        internal static string WhiteSpaces {
            get {
                return ResourceManager.GetString("WhiteSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BuferMAN.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
