//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuferMAN.Form.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuferMAN.Form.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuferMAN (ADMIN).
        /// </summary>
        internal static string AdminWindowTitle {
            get {
                return ResourceManager.GetString("AdminWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your bufers pinned. Please remove some of them and then try to copy again....
        /// </summary>
        internal static string AllBufersPinned {
            get {
                return ResourceManager.GetString("AllBufersPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many characters....
        /// </summary>
        internal static string BigTextBufer {
            get {
                return ResourceManager.GetString("BigTextBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bufer was loaded from storage.
        /// </summary>
        internal static string BuferLoaded {
            get {
                return ResourceManager.GetString("BuferLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more info in menu: Help -&gt;Documentation.
        /// </summary>
        internal static string DocumentationMentioning {
            get {
                return ResourceManager.GetString("DocumentationMentioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileBufer {
            get {
                return ResourceManager.GetString("FileBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Content.
        /// </summary>
        internal static string FileContentsBufer {
            get {
                return ResourceManager.GetString("FileContentsBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string FilesBufer {
            get {
                return ResourceManager.GetString("FilesBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string FolderBufer {
            get {
                return ResourceManager.GetString("FolderBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string FoldersBufer {
            get {
                return ResourceManager.GetString("FoldersBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageBufer {
            get {
                return ResourceManager.GetString("ImageBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit session.
        /// </summary>
        internal static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program is launched in not administrator mode. You can not paste bufers into windows launched in admin mode!
        ///
        ///.
        /// </summary>
        internal static string NotAdminWarning {
            get {
                return ResourceManager.GetString("NotAdminWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuferMAN: Alt+C to open.
        /// </summary>
        internal static string NotifyIconStartupText {
            get {
                return ResourceManager.GetString("NotifyIconStartupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a text.
        /// </summary>
        internal static string NotTextBufer {
            get {
                return ResourceManager.GetString("NotTextBufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tra-ta-ta!!!.
        /// </summary>
        internal static string TratataTitle {
            get {
                return ResourceManager.GetString("TratataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bufer manual.
        /// </summary>
        internal static string TrayMenuBuferManual {
            get {
                return ResourceManager.GetString("TrayMenuBuferManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string TrayMenuOptions {
            get {
                return ResourceManager.GetString("TrayMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click bufer to paste it into active window.
        ///Every bufer has a context menu.
        ///
        ///
        ///Hot keys:
        ///  - Launch the program: Alt + C
        ///  - Go to the first bufer: X (Home)
        ///  - Go to the last bufer: V (End)
        ///  - Tabify through 3 bufers: C
        ///  - Undo/Redo an action: Ctrl + Z, Ctrl + Y
        ///
        ///-&gt; Paste your nice copies!.
        /// </summary>
        internal static string UserManual {
            get {
                return ResourceManager.GetString("UserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white spaces.
        /// </summary>
        internal static string WhiteSpaces {
            get {
                return ResourceManager.GetString("WhiteSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuferMAN.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
